// TodoList Types
export const TODOS_FILL = 'TODOS_FILL';

// AddTodoForm Types
export const SHOW_NEW_TASK_FORM = 'SHOW_NEW_TASK_FORM';
export const CHOOSE_COMPLETE_STATUS = 'CHOOSE_COMPLETE_STATUS';
export const CHANGE_TITLE_INPUT_TEXT = 'CHANGE_TITLE_INPUT_TEXT';
export const CHANGE_DESCRIPTION_INPUT_TEXT = 'CHANGE_DESCRIPTION_INPUT_TEXT';
export const GET_DEADLINE_DATE = 'GET_DEADLINE_DATE';
export const CHANGE_SUBTASK_LIST = 'CHANGE_SUBTASK_LIST';
export const RESET_FORM = 'RESET_FORM';
export const SET_SUBTASK_COMPLETE_STATUS = 'SET_SUBTASK_COMPLETE_STATUS';
export const CHANGE_SUBTASK_INPUT_TEXT = 'CHANGE_SUBTASK_INPUT_TEXT';
export const CHANGE_SELECTED_SUBTASK_TEXT = 'CHANGE_SELECTED_SUBTASK_TEXT';
export const CHANGE_SELECTED_SUBTASK_COMPLETE_STATUS
  = 'CHANGE_SELECTED_SUBTASK_COMPLETE_STATUS';
export const SET_TAG = 'SET_TAG';

// ChangeTodoInfo Types
export const GET_TODO_INFO = 'GET_TODO_INFO';
export const SHOW_TODO_INFO = 'SHOW_TODO_INFO';
export const SET_COMPLETE_STATUS_FOR_SELECTED_TODO
  = 'SET_COMPLETE_STATUS_FOR_SELECTED_TODO';
export const CHANGE_TITLE_FOR_SELECTED_TODO = 'CHANGE_TITLE_FOR_SELECTED_TODO';
export const CHANGE_DEADLINE_FOR_SELECTED_TODO
  = 'CHANGE_DEADLINE_FOR_SELECTED_TODO';
export const CHANGE_DESCRIPTION_FOR_SELECTED_TODO
  = 'CHANGE_DESCRIPTION_FOR_SELECTED_TODO';
export const CHANGE_TODO_INFO = 'CHANGE_TODO_INFO';
export const CHANGE_TODO_SUBTASK_LIST = 'CHANGE_TODO_SUBTASK_LIST';
export const CHANGE_TODO_SUBTASK_INPUT_TEXT = 'CHANGE_SUBTASK_INPUT_TEXT';
export const CHANGE_TODO_SELECTED_SUBTASK_TEXT
  = 'CHANGE_TODO_SELECTED_SUBTASK_TEXT';
export const CHANGE_TODO_SELECTED_SUBTASK_COMPLETE_STATUS
  = 'CHANGE_TODO_SELECTED_SUBTASK_COMPLETE_STATUS';
export const SET_TODO_SUBTASK_COMPLETE_STATUS
  = 'SET_TODO_SUBTASK_COMPLETE_STATUS';
export const CHANGE_TODO_TAG = 'CHANGE_TODO_TAG';
export const RESET_EDITING_SELECTED_TODO_FORM
  = 'RESET_EDITING_SELECTED_TODO_FORM';

// Global Types
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const SET_TITLE_WARNING = 'SET_TITLE_WARNING';
export const SET_TAG_FIELD_WARNING = 'SET_TAG_FIELD_WARNING';
export const SET_SUBTASKS_WARNING = 'SET_SUBTASKS_WARNING';
export const SET_DEADLINE_WARNING = 'SET_DEADLINE_WARNING';
