// TodoList Types
export const TODOS_FILL = 'TODOS_FILL';

// AddTodoForm Types
export const SHOW_NEW_TASK_FORM = 'SHOW_NEW_TASK_FORM';
export const CHOOSE_COMPLETE_STATUS = 'CHOOSE_COMPLETE_STATUS';
export const CHANGE_TITLE_INPUT_TEXT = 'CHANGE_TITLE_INPUT_TEXT';
export const CHANGE_DESCRIPTION_INPUT_TEXT = 'CHANGE_DESCRIPTION_INPUT_TEXT';
export const GET_DEADLINE_DATE = 'GET_DEADLINE_DATE';
export const CHANGE_SUBTASK_INPUT_TEXT = 'CHANGE_SUBTASK_INPUT_TEXT';
export const ADD_SUBTASK = 'ADD_SUBTASK';
export const CHANGE_SUBTASK_LIST = 'CHANGE_SUBTASK_LIST';
export const RESET_FORM = 'RESET_FORM';
export const SET_SUBTASK_COMPLETE_STATUS = 'SET_SUBTASK_COMPLETE_STATUS';
export const CHANGE_SELECTED_SUBTASK_TEXT = 'CHANGE_SELECTED_SUBTASK_TEXT';
export const CHANGE_SELECTED_SUBTASK_COMPLETE_STATUS
  = 'CHANGE_SELECTED_SUBTASK_COMPLETE_STATUS';

// ChangeTodoInfo Types
export const GET_TODO_INFO = 'GET_TODO_INFO';
export const SHOW_TODO_INFO = 'SHOW_TODO_INFO';
export const SET_COMPLETE_STATUS_FOR_SELECTED_TODO
  = 'SET_COMPLETE_STATUS_FOR_SELECTED_TODO';
export const CHANGE_TITLE_FOR_SELECTED_TODO = 'CHANGE_TITLE_FOR_SELECTED_TODO';
export const CHANGE_DEADLINE_FOR_SELECTED_TODO
  = 'CHANGE_DEADLINE_FOR_SELECTED_TODO';
export const CHANGE_DESCRIPTION_FOR_SELECTED_TODO
  = 'CHANGE_DESCRIPTION_FOR_SELECTED_TODO';

// Global Types
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
